version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: exampleDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=exampleDB
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

volumes:
  postgres_data:
