# Generated by Django 5.0.6 on 2024-05-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_service_total_cost_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_cost',
        ),
    ]
