# Generated by Django 5.0.6 on 2024-05-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_service_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service_types',
            field=models.ManyToManyField(to='reservation.servicetype'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
