# Generated by Django 5.0.6 on 2024-05-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_rename_capacity_servicetype_number_of_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='name',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='Service_Name',
            field=models.IntegerField(choices=[(1, 'Room A \n capacity = 10 people'), (2, 'Room B \n capacity = 20 people'), (3, 'Room C \n capacity = 25 people'), (4, 'Room D \n capacity = 50 people'), (5, 'Pool A \n capacity = 10 people'), (6, 'Pool B \n capacity = 20 people'), (7, 'Pool C \n capacity = 25 people'), (8, 'Pool D \n capacity = 50 people')], default=1),
        ),
    ]
