# Generated by Django 5.0.6 on 2024-05-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_rename_number_of_attendees_servicetype_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
    ]
