# Generated by Django 5.0.6 on 2024-05-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_remove_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('special_orders', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
        migrations.CreateModel(
            name='PoolOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.IntegerField(choices=[(1, 'Pool A'), (2, 'Pool B'), (3, 'Pool C'), (4, 'Pool D'), (5, 'Do Not Want To Swim')], default=5)),
                ('attendees', models.IntegerField(default=0)),
                ('special_orders', models.TextField()),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.pooloption')),
                ('room_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.roomoption')),
            ],
        ),
        migrations.AddField(
            model_name='servicetype',
            name='service',
            field=models.ManyToManyField(to='reservation.service'),
        ),
    ]
