# Generated by Django 5.0.6 on 2024-05-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_roomoption_remove_servicetype_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomoption',
            name='name',
        ),
        migrations.AddField(
            model_name='roomoption',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomoption',
            name='room_name',
            field=models.IntegerField(choices=[(1, 'Room A'), (2, 'Room B'), (3, 'Room C'), (4, 'Room D'), (5, 'Do Not Want a Room')], default=5),
        ),
        migrations.AddField(
            model_name='roomoption',
            name='timeslot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot'),
        ),
        migrations.AlterField(
            model_name='pooloption',
            name='timeslot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot'),
        ),
    ]
