# Generated by Django 5.0.6 on 2024-05-30 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_remove_roomoption_name_roomoption_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='estimated_people',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service_types',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pool_option',
        ),
        migrations.RemoveField(
            model_name='service',
            name='room_option',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='hourlyRate',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='service',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ManyToManyField(to='reservation.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ManyToManyField(to='reservation.servicetype'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='pool_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.pooloption'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='room_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.roomoption'),
        ),
    ]
