# Generated by Django 4.2.7 on 2024-06-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_remove_reservation_estimated_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.servicetype'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
