# Generated by Django 5.0.6 on 2024-06-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0012_remove_reservation_estimated_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=40),
        ),
    ]
