# Generated by Django 4.2.7 on 2024-06-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_remove_reservation_service_reservation_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service_type',
            field=models.ManyToManyField(to='reservation.servicetype'),
        ),
    ]
