# Generated by Django 5.0.6 on 2024-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_remove_reservation_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='service_type',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.ManyToManyField(to='reservation.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ManyToManyField(to='reservation.service'),
        ),
    ]
