# Generated by Django 5.0.6 on 2024-06-06 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0013_alter_customer_email"),
        ("reservation", "0015_remove_reservation_service_type_service_and_more"),
    ]

    operations = []
